### ISSUE TITLE
点默阁 — 文章缩略显示文字

### ISSUE THREAD

**Issue by jiale888** [haxibiao/dianmoge#28]
![image.png](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/2ee84742-35cd-49c1-bbf7-80466f8c23c1)
这是两篇不一样的文章，
事件发生是因为，浏览器故障，出现同时发表了两篇同样的文章，由于没有删除按钮，于是在原先的文章进行修改，结果修改完后，发现，两篇截取的文字相同，但是点进去的文字是不同的。
以下是点进去的文字截图。
![image.png](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/1496ceb6-ef13-429f-b672-7f276b8885c2)
![image.png](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/5a743c7c-261c-41e2-a772-b69faff59922)

**Comment by pengconguses1** [comment]
这个跟浏览器有关,
